// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocess_return_overrides.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "coprocess_return_overrides.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace coprocess {

void protobuf_ShutdownFile_coprocess_5freturn_5foverrides_2eproto() {
  ReturnOverrides_default_instance_.Shutdown();
}

void protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  ReturnOverrides_default_instance_.DefaultConstruct();
  ReturnOverrides_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto_once_);
void protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto_once_,
                 &protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto_impl);
}
void protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_coprocess_5freturn_5foverrides_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto_once_);
void protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto_once_,
                 &protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto_impl);
}
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_coprocess_5freturn_5foverrides_2eproto {
  StaticDescriptorInitializer_coprocess_5freturn_5foverrides_2eproto() {
    protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto();
  }
} static_descriptor_initializer_coprocess_5freturn_5foverrides_2eproto_;
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReturnOverrides::kResponseCodeFieldNumber;
const int ReturnOverrides::kResponseErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReturnOverrides::ReturnOverrides()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:coprocess.ReturnOverrides)
}
ReturnOverrides::ReturnOverrides(::google::protobuf::Arena* arena)
  : ::google::protobuf::MessageLite(),
  _arena_ptr_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:coprocess.ReturnOverrides)
}

void ReturnOverrides::InitAsDefaultInstance() {
}

ReturnOverrides::ReturnOverrides(const ReturnOverrides& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:coprocess.ReturnOverrides)
}

void ReturnOverrides::SharedCtor() {
  response_error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  response_code_ = 0;
  _cached_size_ = 0;
}

ReturnOverrides::~ReturnOverrides() {
  // @@protoc_insertion_point(destructor:coprocess.ReturnOverrides)
  SharedDtor();
}

void ReturnOverrides::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

  response_error_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), arena);
}

void ReturnOverrides::ArenaDtor(void* object) {
  ReturnOverrides* _this = reinterpret_cast< ReturnOverrides* >(object);
  (void)_this;
}
void ReturnOverrides::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ReturnOverrides::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ReturnOverrides& ReturnOverrides::default_instance() {
  protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<ReturnOverrides> ReturnOverrides_default_instance_;

ReturnOverrides* ReturnOverrides::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<ReturnOverrides>(arena);
}

void ReturnOverrides::Clear() {
// @@protoc_insertion_point(message_clear_start:coprocess.ReturnOverrides)
  response_code_ = 0;
  response_error_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}

bool ReturnOverrides::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:coprocess.ReturnOverrides)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 response_code = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &response_code_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_response_error;
        break;
      }

      // optional string response_error = 2;
      case 2: {
        if (tag == 18) {
         parse_response_error:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_response_error()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->response_error().data(), this->response_error().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.ReturnOverrides.response_error"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:coprocess.ReturnOverrides)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:coprocess.ReturnOverrides)
  return false;
#undef DO_
}

void ReturnOverrides::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:coprocess.ReturnOverrides)
  // optional int32 response_code = 1;
  if (this->response_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->response_code(), output);
  }

  // optional string response_error = 2;
  if (this->response_error().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_error().data(), this->response_error().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "coprocess.ReturnOverrides.response_error");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->response_error(), output);
  }

  // @@protoc_insertion_point(serialize_end:coprocess.ReturnOverrides)
}

size_t ReturnOverrides::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coprocess.ReturnOverrides)
  size_t total_size = 0;

  // optional int32 response_code = 1;
  if (this->response_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->response_code());
  }

  // optional string response_error = 2;
  if (this->response_error().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->response_error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReturnOverrides::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ReturnOverrides*>(&from));
}

void ReturnOverrides::MergeFrom(const ReturnOverrides& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:coprocess.ReturnOverrides)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void ReturnOverrides::UnsafeMergeFrom(const ReturnOverrides& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.response_code() != 0) {
    set_response_code(from.response_code());
  }
  if (from.response_error().size() > 0) {
    set_response_error(from.response_error());
  }
}

void ReturnOverrides::CopyFrom(const ReturnOverrides& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coprocess.ReturnOverrides)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool ReturnOverrides::IsInitialized() const {

  return true;
}

void ReturnOverrides::Swap(ReturnOverrides* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ReturnOverrides temp;
    temp.UnsafeMergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void ReturnOverrides::UnsafeArenaSwap(ReturnOverrides* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ReturnOverrides::InternalSwap(ReturnOverrides* other) {
  std::swap(response_code_, other->response_code_);
  response_error_.Swap(&other->response_error_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string ReturnOverrides::GetTypeName() const {
  return "coprocess.ReturnOverrides";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReturnOverrides

// optional int32 response_code = 1;
void ReturnOverrides::clear_response_code() {
  response_code_ = 0;
}
::google::protobuf::int32 ReturnOverrides::response_code() const {
  // @@protoc_insertion_point(field_get:coprocess.ReturnOverrides.response_code)
  return response_code_;
}
void ReturnOverrides::set_response_code(::google::protobuf::int32 value) {
  
  response_code_ = value;
  // @@protoc_insertion_point(field_set:coprocess.ReturnOverrides.response_code)
}

// optional string response_error = 2;
void ReturnOverrides::clear_response_error() {
  response_error_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
const ::std::string& ReturnOverrides::response_error() const {
  // @@protoc_insertion_point(field_get:coprocess.ReturnOverrides.response_error)
  return response_error_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ReturnOverrides::set_response_error(const ::std::string& value) {
  
  response_error_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:coprocess.ReturnOverrides.response_error)
}
void ReturnOverrides::set_response_error(const char* value) {
  
  response_error_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:coprocess.ReturnOverrides.response_error)
}
void ReturnOverrides::set_response_error(const char* value,
    size_t size) {
  
  response_error_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:coprocess.ReturnOverrides.response_error)
}
::std::string* ReturnOverrides::mutable_response_error() {
  
  // @@protoc_insertion_point(field_mutable:coprocess.ReturnOverrides.response_error)
  return response_error_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* ReturnOverrides::release_response_error() {
  // @@protoc_insertion_point(field_release:coprocess.ReturnOverrides.response_error)
  
  return response_error_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* ReturnOverrides::unsafe_arena_release_response_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coprocess.ReturnOverrides.response_error)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return response_error_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
void ReturnOverrides::set_allocated_response_error(::std::string* response_error) {
  if (response_error != NULL) {
    
  } else {
    
  }
  response_error_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), response_error,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:coprocess.ReturnOverrides.response_error)
}
void ReturnOverrides::unsafe_arena_set_allocated_response_error(
    ::std::string* response_error) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (response_error != NULL) {
    
  } else {
    
  }
  response_error_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      response_error, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coprocess.ReturnOverrides.response_error)
}

inline const ReturnOverrides* ReturnOverrides::internal_default_instance() {
  return &ReturnOverrides_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace coprocess

// @@protoc_insertion_point(global_scope)
