// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocess_object.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "coprocess_object.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace coprocess {

void protobuf_ShutdownFile_coprocess_5fobject_2eproto() {
  Object_default_instance_.Shutdown();
  Event_default_instance_.Shutdown();
  EventReply_default_instance_.Shutdown();
}

void protobuf_InitDefaults_coprocess_5fobject_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::coprocess::protobuf_InitDefaults_coprocess_5fmini_5frequest_5fobject_2eproto();
  ::coprocess::protobuf_InitDefaults_coprocess_5fsession_5fstate_2eproto();
  ::coprocess::protobuf_InitDefaults_coprocess_5fcommon_2eproto();
  ::google::protobuf::internal::GetEmptyString();
  Object_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  ::google::protobuf::internal::GetEmptyString();
  ::google::protobuf::internal::GetEmptyString();
  Event_default_instance_.DefaultConstruct();
  EventReply_default_instance_.DefaultConstruct();
  Object_default_instance_.get_mutable()->InitAsDefaultInstance();
  Event_default_instance_.get_mutable()->InitAsDefaultInstance();
  EventReply_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_coprocess_5fobject_2eproto_once_);
void protobuf_InitDefaults_coprocess_5fobject_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_coprocess_5fobject_2eproto_once_,
                 &protobuf_InitDefaults_coprocess_5fobject_2eproto_impl);
}
void protobuf_AddDesc_coprocess_5fobject_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_coprocess_5fobject_2eproto();
  ::coprocess::protobuf_AddDesc_coprocess_5fmini_5frequest_5fobject_2eproto();
  ::coprocess::protobuf_AddDesc_coprocess_5fsession_5fstate_2eproto();
  ::coprocess::protobuf_AddDesc_coprocess_5fcommon_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_coprocess_5fobject_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_coprocess_5fobject_2eproto_once_);
void protobuf_AddDesc_coprocess_5fobject_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_coprocess_5fobject_2eproto_once_,
                 &protobuf_AddDesc_coprocess_5fobject_2eproto_impl);
}
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_coprocess_5fobject_2eproto {
  StaticDescriptorInitializer_coprocess_5fobject_2eproto() {
    protobuf_AddDesc_coprocess_5fobject_2eproto();
  }
} static_descriptor_initializer_coprocess_5fobject_2eproto_;
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

void Object::_slow_mutable_request() {
  request_ = ::google::protobuf::Arena::CreateMessage< ::coprocess::MiniRequestObject >(
      GetArenaNoVirtual());
}
::coprocess::MiniRequestObject* Object::_slow_release_request() {
  if (request_ == NULL) {
    return NULL;
  } else {
    ::coprocess::MiniRequestObject* temp = new ::coprocess::MiniRequestObject(*request_);
    request_ = NULL;
    return temp;
  }
}
::coprocess::MiniRequestObject* Object::unsafe_arena_release_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coprocess.Object.request)
  
  ::coprocess::MiniRequestObject* temp = request_;
  request_ = NULL;
  return temp;
}
void Object::_slow_set_allocated_request(
    ::google::protobuf::Arena* message_arena, ::coprocess::MiniRequestObject** request) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*request) == NULL) {
      message_arena->Own(*request);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*request)) {
      ::coprocess::MiniRequestObject* new_request = 
            ::google::protobuf::Arena::CreateMessage< ::coprocess::MiniRequestObject >(
            message_arena);
      new_request->CopyFrom(**request);
      *request = new_request;
    }
}
void Object::unsafe_arena_set_allocated_request(
    ::coprocess::MiniRequestObject* request) {
  if (GetArenaNoVirtual() == NULL) {
    delete request_;
  }
  request_ = request;
  if (request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coprocess.Object.request)
}
void Object::_slow_mutable_session() {
  session_ = ::google::protobuf::Arena::CreateMessage< ::coprocess::SessionState >(
      GetArenaNoVirtual());
}
::coprocess::SessionState* Object::_slow_release_session() {
  if (session_ == NULL) {
    return NULL;
  } else {
    ::coprocess::SessionState* temp = new ::coprocess::SessionState(*session_);
    session_ = NULL;
    return temp;
  }
}
::coprocess::SessionState* Object::unsafe_arena_release_session() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coprocess.Object.session)
  
  ::coprocess::SessionState* temp = session_;
  session_ = NULL;
  return temp;
}
void Object::_slow_set_allocated_session(
    ::google::protobuf::Arena* message_arena, ::coprocess::SessionState** session) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*session) == NULL) {
      message_arena->Own(*session);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*session)) {
      ::coprocess::SessionState* new_session = 
            ::google::protobuf::Arena::CreateMessage< ::coprocess::SessionState >(
            message_arena);
      new_session->CopyFrom(**session);
      *session = new_session;
    }
}
void Object::unsafe_arena_set_allocated_session(
    ::coprocess::SessionState* session) {
  if (GetArenaNoVirtual() == NULL) {
    delete session_;
  }
  session_ = session;
  if (session) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coprocess.Object.session)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Object::kHookTypeFieldNumber;
const int Object::kHookNameFieldNumber;
const int Object::kRequestFieldNumber;
const int Object::kSessionFieldNumber;
const int Object::kMetadataFieldNumber;
const int Object::kSpecFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Object::Object()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_coprocess_5fobject_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:coprocess.Object)
}
Object::Object(::google::protobuf::Arena* arena)
  : ::google::protobuf::MessageLite(),
  _arena_ptr_(arena),
  metadata_(arena),
  spec_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_InitDefaults_coprocess_5fobject_2eproto();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:coprocess.Object)
}

void Object::InitAsDefaultInstance() {
  request_ = const_cast< ::coprocess::MiniRequestObject*>(
      ::coprocess::MiniRequestObject::internal_default_instance());
  session_ = const_cast< ::coprocess::SessionState*>(
      ::coprocess::SessionState::internal_default_instance());
}

Object::Object(const Object& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:coprocess.Object)
}

void Object::SharedCtor() {
  hook_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_ = NULL;
  session_ = NULL;
  hook_type_ = 0;
  _cached_size_ = 0;
}

Object::~Object() {
  // @@protoc_insertion_point(destructor:coprocess.Object)
  SharedDtor();
}

void Object::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

  hook_name_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), arena);
  if (this != &Object_default_instance_.get()) {
    delete request_;
    delete session_;
  }
}

void Object::ArenaDtor(void* object) {
  Object* _this = reinterpret_cast< Object* >(object);
  (void)_this;
}
void Object::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void Object::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Object& Object::default_instance() {
  protobuf_InitDefaults_coprocess_5fobject_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<Object> Object_default_instance_;

Object* Object::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<Object>(arena);
}

void Object::Clear() {
// @@protoc_insertion_point(message_clear_start:coprocess.Object)
  hook_type_ = 0;
  hook_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  if (GetArenaNoVirtual() == NULL && request_ != NULL) delete request_;
  request_ = NULL;
  if (GetArenaNoVirtual() == NULL && session_ != NULL) delete session_;
  session_ = NULL;
  metadata_.Clear();
  spec_.Clear();
}

bool Object::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:coprocess.Object)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .coprocess.HookType hook_type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_hook_type(static_cast< ::coprocess::HookType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_hook_name;
        break;
      }

      // optional string hook_name = 2;
      case 2: {
        if (tag == 18) {
         parse_hook_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hook_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hook_name().data(), this->hook_name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.Object.hook_name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_request;
        break;
      }

      // optional .coprocess.MiniRequestObject request = 3;
      case 3: {
        if (tag == 26) {
         parse_request:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_request()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_session;
        break;
      }

      // optional .coprocess.SessionState session = 4;
      case 4: {
        if (tag == 34) {
         parse_session:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_session()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_metadata;
        break;
      }

      // map<string, string> metadata = 5;
      case 5: {
        if (tag == 42) {
         parse_metadata:
          DO_(input->IncrementRecursionDepth());
         parse_loop_metadata:
          Object_MetadataEntry::Parser< ::google::protobuf::internal::MapFieldLite<
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&metadata_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), parser.key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.Object.MetadataEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), parser.value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.Object.MetadataEntry.value"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_loop_metadata;
        if (input->ExpectTag(50)) goto parse_loop_spec;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // map<string, string> spec = 6;
      case 6: {
        if (tag == 50) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_spec:
          Object_SpecEntry::Parser< ::google::protobuf::internal::MapFieldLite<
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&spec_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), parser.key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.Object.SpecEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), parser.value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.Object.SpecEntry.value"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_loop_spec;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:coprocess.Object)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:coprocess.Object)
  return false;
#undef DO_
}

void Object::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:coprocess.Object)
  // optional .coprocess.HookType hook_type = 1;
  if (this->hook_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->hook_type(), output);
  }

  // optional string hook_name = 2;
  if (this->hook_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hook_name().data(), this->hook_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "coprocess.Object.hook_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->hook_name(), output);
  }

  // optional .coprocess.MiniRequestObject request = 3;
  if (this->has_request()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, *this->request_, output);
  }

  // optional .coprocess.SessionState session = 4;
  if (this->has_session()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, *this->session_, output);
  }

  // map<string, string> metadata = 5;
  if (!this->metadata().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), p->first.length(),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "coprocess.Object.MetadataEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), p->second.length(),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "coprocess.Object.MetadataEntry.value");
      }
    };

    if (output->IsSerializationDeterminstic() &&
        this->metadata().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->metadata().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->metadata().begin();
          it != this->metadata().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<Object_MetadataEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(metadata_.NewEntryWrapper(
            items[i]->first, items[i]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessage(
            5, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[i]);
      }
    } else {
      ::google::protobuf::scoped_ptr<Object_MetadataEntry> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->metadata().begin();
          it != this->metadata().end(); ++it) {
        entry.reset(metadata_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessage(
            5, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  // map<string, string> spec = 6;
  if (!this->spec().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), p->first.length(),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "coprocess.Object.SpecEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), p->second.length(),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "coprocess.Object.SpecEntry.value");
      }
    };

    if (output->IsSerializationDeterminstic() &&
        this->spec().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->spec().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->spec().begin();
          it != this->spec().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<Object_SpecEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(spec_.NewEntryWrapper(
            items[i]->first, items[i]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessage(
            6, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[i]);
      }
    } else {
      ::google::protobuf::scoped_ptr<Object_SpecEntry> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->spec().begin();
          it != this->spec().end(); ++it) {
        entry.reset(spec_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessage(
            6, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  // @@protoc_insertion_point(serialize_end:coprocess.Object)
}

size_t Object::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coprocess.Object)
  size_t total_size = 0;

  // optional .coprocess.HookType hook_type = 1;
  if (this->hook_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->hook_type());
  }

  // optional string hook_name = 2;
  if (this->hook_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hook_name());
  }

  // optional .coprocess.MiniRequestObject request = 3;
  if (this->has_request()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->request_);
  }

  // optional .coprocess.SessionState session = 4;
  if (this->has_session()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->session_);
  }

  // map<string, string> metadata = 5;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->metadata_size());
  {
    ::google::protobuf::scoped_ptr<Object_MetadataEntry> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->metadata().begin();
        it != this->metadata().end(); ++it) {
      if (entry.get() != NULL && entry->GetArena() != NULL) {
        entry.release();
      }
      entry.reset(metadata_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
    if (entry.get() != NULL && entry->GetArena() != NULL) {
      entry.release();
    }
  }

  // map<string, string> spec = 6;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->spec_size());
  {
    ::google::protobuf::scoped_ptr<Object_SpecEntry> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->spec().begin();
        it != this->spec().end(); ++it) {
      if (entry.get() != NULL && entry->GetArena() != NULL) {
        entry.release();
      }
      entry.reset(spec_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
    if (entry.get() != NULL && entry->GetArena() != NULL) {
      entry.release();
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Object::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Object*>(&from));
}

void Object::MergeFrom(const Object& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:coprocess.Object)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void Object::UnsafeMergeFrom(const Object& from) {
  GOOGLE_DCHECK(&from != this);
  metadata_.MergeFrom(from.metadata_);
  spec_.MergeFrom(from.spec_);
  if (from.hook_type() != 0) {
    set_hook_type(from.hook_type());
  }
  if (from.hook_name().size() > 0) {
    set_hook_name(from.hook_name());
  }
  if (from.has_request()) {
    mutable_request()->::coprocess::MiniRequestObject::MergeFrom(from.request());
  }
  if (from.has_session()) {
    mutable_session()->::coprocess::SessionState::MergeFrom(from.session());
  }
}

void Object::CopyFrom(const Object& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coprocess.Object)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool Object::IsInitialized() const {

  return true;
}

void Object::Swap(Object* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    Object temp;
    temp.UnsafeMergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void Object::UnsafeArenaSwap(Object* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void Object::InternalSwap(Object* other) {
  std::swap(hook_type_, other->hook_type_);
  hook_name_.Swap(&other->hook_name_);
  std::swap(request_, other->request_);
  std::swap(session_, other->session_);
  metadata_.Swap(&other->metadata_);
  spec_.Swap(&other->spec_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string Object::GetTypeName() const {
  return "coprocess.Object";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Object

// optional .coprocess.HookType hook_type = 1;
void Object::clear_hook_type() {
  hook_type_ = 0;
}
::coprocess::HookType Object::hook_type() const {
  // @@protoc_insertion_point(field_get:coprocess.Object.hook_type)
  return static_cast< ::coprocess::HookType >(hook_type_);
}
void Object::set_hook_type(::coprocess::HookType value) {
  
  hook_type_ = value;
  // @@protoc_insertion_point(field_set:coprocess.Object.hook_type)
}

// optional string hook_name = 2;
void Object::clear_hook_name() {
  hook_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
const ::std::string& Object::hook_name() const {
  // @@protoc_insertion_point(field_get:coprocess.Object.hook_name)
  return hook_name_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Object::set_hook_name(const ::std::string& value) {
  
  hook_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:coprocess.Object.hook_name)
}
void Object::set_hook_name(const char* value) {
  
  hook_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:coprocess.Object.hook_name)
}
void Object::set_hook_name(const char* value,
    size_t size) {
  
  hook_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:coprocess.Object.hook_name)
}
::std::string* Object::mutable_hook_name() {
  
  // @@protoc_insertion_point(field_mutable:coprocess.Object.hook_name)
  return hook_name_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* Object::release_hook_name() {
  // @@protoc_insertion_point(field_release:coprocess.Object.hook_name)
  
  return hook_name_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* Object::unsafe_arena_release_hook_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coprocess.Object.hook_name)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return hook_name_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
void Object::set_allocated_hook_name(::std::string* hook_name) {
  if (hook_name != NULL) {
    
  } else {
    
  }
  hook_name_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hook_name,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:coprocess.Object.hook_name)
}
void Object::unsafe_arena_set_allocated_hook_name(
    ::std::string* hook_name) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (hook_name != NULL) {
    
  } else {
    
  }
  hook_name_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      hook_name, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coprocess.Object.hook_name)
}

// optional .coprocess.MiniRequestObject request = 3;
bool Object::has_request() const {
  return this != internal_default_instance() && request_ != NULL;
}
void Object::clear_request() {
  if (GetArenaNoVirtual() == NULL && request_ != NULL) delete request_;
  request_ = NULL;
}
const ::coprocess::MiniRequestObject& Object::request() const {
  // @@protoc_insertion_point(field_get:coprocess.Object.request)
  return request_ != NULL ? *request_
                         : *::coprocess::MiniRequestObject::internal_default_instance();
}
::coprocess::MiniRequestObject* Object::mutable_request() {
  
  if (request_ == NULL) {
    _slow_mutable_request();
  }
  // @@protoc_insertion_point(field_mutable:coprocess.Object.request)
  return request_;
}
::coprocess::MiniRequestObject* Object::release_request() {
  // @@protoc_insertion_point(field_release:coprocess.Object.request)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_request();
  } else {
    ::coprocess::MiniRequestObject* temp = request_;
    request_ = NULL;
    return temp;
  }
}
 void Object::set_allocated_request(::coprocess::MiniRequestObject* request) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete request_;
  }
  if (request != NULL) {
    _slow_set_allocated_request(message_arena, &request);
  }
  request_ = request;
  if (request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:coprocess.Object.request)
}

// optional .coprocess.SessionState session = 4;
bool Object::has_session() const {
  return this != internal_default_instance() && session_ != NULL;
}
void Object::clear_session() {
  if (GetArenaNoVirtual() == NULL && session_ != NULL) delete session_;
  session_ = NULL;
}
const ::coprocess::SessionState& Object::session() const {
  // @@protoc_insertion_point(field_get:coprocess.Object.session)
  return session_ != NULL ? *session_
                         : *::coprocess::SessionState::internal_default_instance();
}
::coprocess::SessionState* Object::mutable_session() {
  
  if (session_ == NULL) {
    _slow_mutable_session();
  }
  // @@protoc_insertion_point(field_mutable:coprocess.Object.session)
  return session_;
}
::coprocess::SessionState* Object::release_session() {
  // @@protoc_insertion_point(field_release:coprocess.Object.session)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_session();
  } else {
    ::coprocess::SessionState* temp = session_;
    session_ = NULL;
    return temp;
  }
}
 void Object::set_allocated_session(::coprocess::SessionState* session) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete session_;
  }
  if (session != NULL) {
    _slow_set_allocated_session(message_arena, &session);
  }
  session_ = session;
  if (session) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:coprocess.Object.session)
}

// map<string, string> metadata = 5;
int Object::metadata_size() const {
  return metadata_.size();
}
void Object::clear_metadata() {
  metadata_.Clear();
}
 const ::google::protobuf::Map< ::std::string, ::std::string >&
Object::metadata() const {
  // @@protoc_insertion_point(field_map:coprocess.Object.metadata)
  return metadata_.GetMap();
}
 ::google::protobuf::Map< ::std::string, ::std::string >*
Object::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_map:coprocess.Object.metadata)
  return metadata_.MutableMap();
}

// map<string, string> spec = 6;
int Object::spec_size() const {
  return spec_.size();
}
void Object::clear_spec() {
  spec_.Clear();
}
 const ::google::protobuf::Map< ::std::string, ::std::string >&
Object::spec() const {
  // @@protoc_insertion_point(field_map:coprocess.Object.spec)
  return spec_.GetMap();
}
 ::google::protobuf::Map< ::std::string, ::std::string >*
Object::mutable_spec() {
  // @@protoc_insertion_point(field_mutable_map:coprocess.Object.spec)
  return spec_.MutableMap();
}

inline const Object* Object::internal_default_instance() {
  return &Object_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Event::kPayloadFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Event::Event()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_coprocess_5fobject_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:coprocess.Event)
}
Event::Event(::google::protobuf::Arena* arena)
  : ::google::protobuf::MessageLite(),
  _arena_ptr_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_InitDefaults_coprocess_5fobject_2eproto();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:coprocess.Event)
}

void Event::InitAsDefaultInstance() {
}

Event::Event(const Event& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:coprocess.Event)
}

void Event::SharedCtor() {
  payload_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

Event::~Event() {
  // @@protoc_insertion_point(destructor:coprocess.Event)
  SharedDtor();
}

void Event::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

  payload_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), arena);
}

void Event::ArenaDtor(void* object) {
  Event* _this = reinterpret_cast< Event* >(object);
  (void)_this;
}
void Event::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void Event::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Event& Event::default_instance() {
  protobuf_InitDefaults_coprocess_5fobject_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<Event> Event_default_instance_;

Event* Event::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<Event>(arena);
}

void Event::Clear() {
// @@protoc_insertion_point(message_clear_start:coprocess.Event)
  payload_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}

bool Event::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:coprocess.Event)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string payload = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_payload()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->payload().data(), this->payload().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.Event.payload"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:coprocess.Event)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:coprocess.Event)
  return false;
#undef DO_
}

void Event::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:coprocess.Event)
  // optional string payload = 1;
  if (this->payload().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->payload().data(), this->payload().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "coprocess.Event.payload");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->payload(), output);
  }

  // @@protoc_insertion_point(serialize_end:coprocess.Event)
}

size_t Event::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coprocess.Event)
  size_t total_size = 0;

  // optional string payload = 1;
  if (this->payload().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->payload());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Event::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Event*>(&from));
}

void Event::MergeFrom(const Event& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:coprocess.Event)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void Event::UnsafeMergeFrom(const Event& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.payload().size() > 0) {
    set_payload(from.payload());
  }
}

void Event::CopyFrom(const Event& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coprocess.Event)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool Event::IsInitialized() const {

  return true;
}

void Event::Swap(Event* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    Event temp;
    temp.UnsafeMergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void Event::UnsafeArenaSwap(Event* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void Event::InternalSwap(Event* other) {
  payload_.Swap(&other->payload_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string Event::GetTypeName() const {
  return "coprocess.Event";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Event

// optional string payload = 1;
void Event::clear_payload() {
  payload_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
const ::std::string& Event::payload() const {
  // @@protoc_insertion_point(field_get:coprocess.Event.payload)
  return payload_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Event::set_payload(const ::std::string& value) {
  
  payload_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:coprocess.Event.payload)
}
void Event::set_payload(const char* value) {
  
  payload_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:coprocess.Event.payload)
}
void Event::set_payload(const char* value,
    size_t size) {
  
  payload_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:coprocess.Event.payload)
}
::std::string* Event::mutable_payload() {
  
  // @@protoc_insertion_point(field_mutable:coprocess.Event.payload)
  return payload_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* Event::release_payload() {
  // @@protoc_insertion_point(field_release:coprocess.Event.payload)
  
  return payload_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* Event::unsafe_arena_release_payload() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coprocess.Event.payload)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return payload_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
void Event::set_allocated_payload(::std::string* payload) {
  if (payload != NULL) {
    
  } else {
    
  }
  payload_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:coprocess.Event.payload)
}
void Event::unsafe_arena_set_allocated_payload(
    ::std::string* payload) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (payload != NULL) {
    
  } else {
    
  }
  payload_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      payload, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coprocess.Event.payload)
}

inline const Event* Event::internal_default_instance() {
  return &Event_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EventReply::EventReply()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_coprocess_5fobject_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:coprocess.EventReply)
}
EventReply::EventReply(::google::protobuf::Arena* arena)
  : ::google::protobuf::MessageLite(),
  _arena_ptr_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_InitDefaults_coprocess_5fobject_2eproto();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:coprocess.EventReply)
}

void EventReply::InitAsDefaultInstance() {
}

EventReply::EventReply(const EventReply& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:coprocess.EventReply)
}

void EventReply::SharedCtor() {
  _cached_size_ = 0;
}

EventReply::~EventReply() {
  // @@protoc_insertion_point(destructor:coprocess.EventReply)
  SharedDtor();
}

void EventReply::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

}

void EventReply::ArenaDtor(void* object) {
  EventReply* _this = reinterpret_cast< EventReply* >(object);
  (void)_this;
}
void EventReply::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void EventReply::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const EventReply& EventReply::default_instance() {
  protobuf_InitDefaults_coprocess_5fobject_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<EventReply> EventReply_default_instance_;

EventReply* EventReply::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<EventReply>(arena);
}

void EventReply::Clear() {
// @@protoc_insertion_point(message_clear_start:coprocess.EventReply)
}

bool EventReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:coprocess.EventReply)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:coprocess.EventReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:coprocess.EventReply)
  return false;
#undef DO_
}

void EventReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:coprocess.EventReply)
  // @@protoc_insertion_point(serialize_end:coprocess.EventReply)
}

size_t EventReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coprocess.EventReply)
  size_t total_size = 0;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EventReply::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const EventReply*>(&from));
}

void EventReply::MergeFrom(const EventReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:coprocess.EventReply)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void EventReply::UnsafeMergeFrom(const EventReply& from) {
  GOOGLE_DCHECK(&from != this);
}

void EventReply::CopyFrom(const EventReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coprocess.EventReply)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool EventReply::IsInitialized() const {

  return true;
}

void EventReply::Swap(EventReply* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    EventReply temp;
    temp.UnsafeMergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void EventReply::UnsafeArenaSwap(EventReply* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void EventReply::InternalSwap(EventReply* other) {
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string EventReply::GetTypeName() const {
  return "coprocess.EventReply";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EventReply

inline const EventReply* EventReply::internal_default_instance() {
  return &EventReply_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace coprocess

// @@protoc_insertion_point(global_scope)
