// Code generated by protoc-gen-go.
// source: coprocess_common.proto
// DO NOT EDIT!

/*
Package coprocess is a generated protocol buffer package.

It is generated from these files:
	coprocess_common.proto
	coprocess_mini_request_object.proto
	coprocess_object.proto
	coprocess_return_overrides.proto
	coprocess_session_state.proto

It has these top-level messages:
	StringSlice
	MiniRequestObject
	Object
	Event
	EventReply
	ReturnOverrides
	AccessSpec
	AccessDefinition
	BasicAuthData
	JWTData
	Monitor
	SessionState
*/
package coprocess

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HookType int32

const (
	HookType_Unknown        HookType = 0
	HookType_Pre            HookType = 1
	HookType_Post           HookType = 2
	HookType_PostKeyAuth    HookType = 3
	HookType_CustomKeyCheck HookType = 4
)

var HookType_name = map[int32]string{
	0: "Unknown",
	1: "Pre",
	2: "Post",
	3: "PostKeyAuth",
	4: "CustomKeyCheck",
}
var HookType_value = map[string]int32{
	"Unknown":        0,
	"Pre":            1,
	"Post":           2,
	"PostKeyAuth":    3,
	"CustomKeyCheck": 4,
}

func (x HookType) String() string {
	return proto.EnumName(HookType_name, int32(x))
}
func (HookType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StringSlice struct {
	Items []string `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *StringSlice) Reset()                    { *m = StringSlice{} }
func (m *StringSlice) String() string            { return proto.CompactTextString(m) }
func (*StringSlice) ProtoMessage()               {}
func (*StringSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*StringSlice)(nil), "coprocess.StringSlice")
	proto.RegisterEnum("coprocess.HookType", HookType_name, HookType_value)
}

func init() { proto.RegisterFile("coprocess_common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0xce, 0x2f, 0x28,
	0xca, 0x4f, 0x4e, 0x2d, 0x2e, 0x8e, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x8b, 0x2b, 0x29, 0x73, 0x71, 0x07, 0x97, 0x14, 0x65, 0xe6, 0xa5,
	0x07, 0xe7, 0x64, 0x26, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0x66, 0x96, 0xa4, 0xe6, 0x16, 0x4b, 0x30,
	0x2a, 0x30, 0x6b, 0x70, 0x06, 0x41, 0x38, 0x5a, 0xfe, 0x5c, 0x1c, 0x1e, 0xf9, 0xf9, 0xd9, 0x21,
	0x95, 0x05, 0xa9, 0x42, 0xdc, 0x5c, 0xec, 0xa1, 0x79, 0xd9, 0x79, 0xf9, 0xe5, 0x79, 0x02, 0x0c,
	0x42, 0xec, 0x5c, 0xcc, 0x01, 0x45, 0xa9, 0x02, 0x8c, 0x42, 0x1c, 0x5c, 0x2c, 0x01, 0xf9, 0xc5,
	0x25, 0x02, 0x4c, 0x42, 0xfc, 0x5c, 0xdc, 0x20, 0x96, 0x77, 0x6a, 0xa5, 0x63, 0x69, 0x49, 0x86,
	0x00, 0xb3, 0x90, 0x10, 0x17, 0x9f, 0x73, 0x69, 0x71, 0x49, 0x7e, 0xae, 0x77, 0x6a, 0xa5, 0x73,
	0x46, 0x6a, 0x72, 0xb6, 0x00, 0x8b, 0x13, 0xab, 0x07, 0xf3, 0x0f, 0x46, 0xc6, 0x24, 0x36, 0xb0,
	0x73, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x4d, 0x24, 0x4b, 0xa8, 0x00, 0x00, 0x00,
}
